export const UPDATE_PERSONAL_POSTS = "UPDATE_PERSONAL_POSTS";
export const UPDATE_FRIEND_POSTS = "UPDATE_FRIEND_POSTS";
export const UPDATE_PROFILE_PIC = "UPDATE_PROFILE_PIC";
export const UPDATE_PROFILE_BIO = "UPDATE_PROFILE_BIO";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

